name: Daily NARS Check

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions: # 명시적으로 권한 부여
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py

      - name: Auto Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update last post ID"
          file_pattern: 'last_post.txt'
